### ISSUE TITLE
Fix image security issues

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-ibmcloud#115]
/kind bug
/sig ibmcloud

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

If you go to https://quay.io/repository/cluster-api-provider-ibmcloud/ibmcloud-cluster-api-controller/manifest/sha256:a920d9ccc5ef600a30911073d491cdc8c500ce6c9a24880d3f0c72a0b9e61af1?tab=vulnerabilities , you will see some security holes are listed.

@morvencao

**Comment by hchenxa** [comment]
may we we can change to use debian:stretch-slim as the base docker image

**Comment by morvencao** [comment]
Why not use `static` lib when building the go binary and replace the base image with `scratch`, to minimize the image size?

**Comment by morvencao** [comment]
Just ignore the last comment, we need `ca-certificates` package to generate the cert/key pair.

**Comment by morvencao** [comment]
Look like simply adding `apt-get update && apt-get upgrade -y` can't upgrade the vulnerable package to fixed version. 

Also checked the images of openstack and vsphere, the same security issues exist.

Should we consider change the base image?

@gyliu513 Any comments?

**Comment by gyliu513** [comment]
@morvencao Yes, you can fix those issues together for OpenStack, vSphere as well.

**Comment by jichenjc** [comment]
@morvencao do we have best practice ?I think other k8s related project have similar question?
and do aws has this kind of issue? maybe we can refer to their stuffs?

**Comment by morvencao** [comment]
@jichenjc Usually we fix this kind of security issues by upgrading the packages to the new version, because new versions contain the fix, however, it doesn't work in provider images, also tried to replace base image. 

I found that the gcp provider is using the `gcr.io/distroless/static:latest` as base image: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/master/Dockerfile#L20, but I don't think we can do that, because we need `ca-certificate` package.

**Comment by wanghh2000** [comment]
Will check the other 2 bugs for cluster-api-provider-openstack and cluster-api-provider-vsphere.
