### ISSUE TITLE
CI jobs failed for release-0.7/0.8

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#1893]
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**
https://prow.ppc64le-cloud.cis.ibm.net/?job=periodic-capi-provider-ibmcloud-e2e-vpc-release-0.8
https://prow.ppc64le-cloud.cis.ibm.net/?job=periodic-capi-provider-ibmcloud-e2e-powervs-release-0.7

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by Amulyam24** [comment]
**Findings:**

**`PowerVS relaase-0.8 job`** failure was due to the VM creation stuck in `BUILD` state and the machine did not come up within the intended time period, the job has time out. This could be due to an infra issue
Region/Zone: osa/osa21


**`VPC release-0.7 job`**  failure was due to error

> "Reconciler error" err="failed to bind port 6443 to control plane create-workload-cluster-vj040x/capibm-e2e-jkie1z-control-plane-5xcjf: load balancer is not in active state" 
Region/Zone: br-sao

**Comment by mkumatag** [comment]
we are not seeing these failures anymore, hence closing this issue.
