### ISSUE TITLE
prefer to use private network to connect the apiserver

### ISSUE THREAD

**Issue by hchenxa** [kubernetes-sigs/cluster-api-provider-ibmcloud#196]
/kind feature
/sig ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
currently, when deploy the kubernetes cluster, the calico and other component use public network. 

refer the kubelet configuration:
```
root@ibmcloud-master-nnpdj:/etc/kubernetes# cat kubelet.conf  | grep server
    server: https://108.168.190.85:443
```

cc @gyliu513 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by gyliu513** [comment]
+1 for this, I think we need to update the logic of post install script in user-data?

FYI @xunpan @jichenjc

**Comment by xunpan** [comment]
make sense.

**Comment by jichenjc** [comment]
it has a set of deep buried into cluster-api logic, long story short, the 
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/master/pkg/cloud/ibmcloud/deployer.go#L48
will be used as IP 

https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/master/pkg/cloud/ibmcloud/actuators/machine/actuator.go#L297

need to be changed to return private IP instead of public IP... we need make sure if we change to private IP it won't affect other functionalities

**Comment by xunpan** [comment]
I guess this code should not be changed.

The annotation of public IP address is used to access target Kubernetes cluster. We cannot access cloud kubernetes with private IP address.
I think private IP should be used for target kubernetes cluster internal communication only.

**Comment by hchenxa** [comment]
right, and agree with Xun that we can only use the private network in user-data when setup the kubeadm.

**Comment by jichenjc** [comment]
that's my assumption to keep the public IP as I am not sure the side effect is, then we need a way to get the private IP by adding some logic (of course we can use linux command to query but I am not sure that's a very good way)

as I said, the logic is buried in cluster-api and I think by design they are using 
https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/apis/cluster/v1alpha1/cluster_types.go#L91
 to represent API to talk to and it's a []

so if we can follow the usage it will be best fit

**Comment by jichenjc** [comment]
```
kubectl --kubeconfig=kubeconfig  get cluster -o yaml
apiVersion: v1
items:
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Cluster
  metadata:
    creationTimestamp: "2019-05-29T01:10:02Z"
    finalizers:
    - cluster.cluster.k8s.io
    generation: 1
    name: test1
    namespace: default
    resourceVersion: "635"
    selfLink: /apis/cluster.k8s.io/v1alpha1/namespaces/default/clusters/test1
    uid: 7cb99130-81ae-11e9-a990-06ff81beb4c6
  spec:
    clusterNetwork:
      pods:
        cidrBlocks:
        - 192.168.0.0/16
      serviceDomain: cluster.local
      services:
        cidrBlocks:
        - 172.31.0.0/16
    providerSpec:
      value:
        apiVersion: ibmcloudclusterproviderconfig/v1alpha1
        kind: IbmcloudClusterProviderSpec
  status:
    apiEndpoints:
    - host: 108.168.190.92
      port: 443
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
