### ISSUE TITLE
Allow to configure node disk storage during vm setup

### ISSUE THREAD

**Issue by FischerLGLN** [kubernetes-sigs/cluster-api-provider-ibmcloud#977]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
VPC ibmcloud 0.3.1
20 GB default storage for gpu profile nodes and control plane nodes aren't much.
Please allow setting the GB amount of boot volume in cluster-api or pick a reasonable default.

See here for vsphere diskgib setting: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/templates/cluster-template.yaml#L49

**Comment by mkumatag** [comment]
The default size is chosen as 20GB because of the boot image size used for creating these vms, e.g:

```shell
$ qemu-img info capibm-vpc-ubuntu-2004-kube-v1-25-2.qcow2
image: capibm-vpc-ubuntu-2004-kube-v1-25-2.qcow2
file format: qcow2
virtual size: 20 GiB (21474836480 bytes).   <======================= 20GB
disk size: 3.93 GiB
cluster_size: 65536
Format specific information:
    compat: 1.1
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
```

Till we fix the issue in our controller, you can change the size [here](https://github.com/kubernetes-sigs/image-builder/blob/9ef11e56c70a88cd2f5230f8e09912e912d9b410/images/capi/packer/qemu/packer.json#L158) and rebuild the image and use it for the nodes
